# Generated by Django 5.0.6 on 2024-06-25 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_cuenta_fechaingreso_alter_obra_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 24, 20, 48, 8, 916089)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 24, 20, 48, 8, 916089)),
        ),
    ]
