# Generated by Django 5.0.6 on 2024-06-25 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_nombreusuario_historialcompra_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('archivo_pdf', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='HistorialCompra',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 15, 21, 31, 536653)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 15, 21, 31, 536653)),
        ),
    ]
