# Generated by Django 5.0.6 on 2024-06-25 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_historialpago_delete_historialcompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 15, 29, 52, 109146)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 15, 29, 52, 110144)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obra'),
        ),
    ]
