# Generated by Django 5.0.6 on 2024-06-26 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_historialcompras_delete_historialpago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 23, 16, 58, 456165)),
        ),
        migrations.AlterField(
            model_name='historialcompras',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 23, 16, 58, 463590)),
        ),
    ]
