# Generated by Django 5.0.6 on 2024-06-26 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_cuenta_fechaingreso_alter_obra_fechaingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompras',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='historialcompras',
            name='datos',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 0, 33, 4, 479664)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 0, 33, 4, 479664)),
        ),
    ]
