# Generated by Django 5.0.6 on 2024-06-26 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_historialcompras_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 3, 35, 32, 199867)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 3, 35, 32, 200867)),
        ),
    ]
