# Generated by Django 5.0.6 on 2024-07-13 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_cuenta_fechaingreso_alter_obra_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 7, 13, 17, 46, 51, 48476)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 7, 13, 17, 46, 51, 49477)),
        ),
    ]
